services:
  # Base de Datos MySQL 8.0
  db:
    image: mysql:8.0
    container_name: arcani-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # <--- CAMBIADO: Ahora DBeaver usará el 3306
    volumes:
      - arcani_mysql_data:/var/lib/mysql

 # --- Backend API Gateway (COMENTADO PARA DESARROLLO LOCAL) ---
  # api-gateway:
  #   build:
  #     context: .
  #     dockerfile: apps/api-gateway/Dockerfile
  #   container_name: arcani-api
  #   restart: always
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=3306

volumes:
  arcani_mysql_data:

